import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import HeroB from "./components/HeroB";

export const metadata: Metadata = {
  title: "HomeBridge AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="overflow-hidden">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
